export const ErrorMessages: any = {
    SuperAdministratorsCannotCreateAcademyRequest: "super_administrators_cannot_create_academy_request",
    AcademyRequestRoleIsInvalid: "academy_request_role_is_invalid",
    TheUserAlreadyExistInTheAcademyWithRole: "user_already_exists_in_academy_with_role",
    TheUserAlreadyExistInTheAcademy: "user_already_exists_in_academy",
    AdministratorCannotEnrollTheCourse: "administrator_cannot_enroll_course",
    TheUserAlreadyEnrolledToTheCourse: "user_already_enrolled_in_course",
    YouAlreadySentAnAcademyRequest: "already_sent_academy_request",
    AcademyRequestNotFound: "academy_request_not_found",
    UserNotFound: "user_not_found",
    AcademyRequestAlreadyApproved: "academy_request_already_approved",
    AddUserToAcademyFailed: "add_user_to_academy_failed",
    AcademyRequestAlreadyRejected: "academy_request_already_rejected",
    InvalidRequest: "an_unexpected_error_has_occurred",
    MakeUpRecordAlreadyExists: "make_up_record_already_exists",
    OriginalLessonAlreadyHasMakeUp: "original_lesson_already_has_make_up",
    MakeupLessonTimeConflict: "makeup_lesson_time_conflict",
    MakeupLessonConflictWithAnotherMakeup: "makeup_lesson_conflict_with_another_makeup",
    TheMakeupLessonIsNotStartedYet: "the_makeup_lesson_is_not_started_yet",
    TheMakeupLessonHasEnded: "the_makeup_lesson_has_ended",
    TemplateNotFound: "template_messages.template_not_found",
    RequiredTemplateName: "template_messages.required_template_name",
    RequiredTemplateContent: "template_messages.required_template_content",
    CannotUpdateGlobalTemplate: "template_messages.cannot_update_global_template",
    CannotDeleteGlobalTemplate: "template_messages.cannot_delete_global_template",
    ExistIncompleteExamSession: "exist_incomplete_exam_session",
    StartTimeMustBeInPast: "start_time_must_be_in_past",
    StoppedTimeMustBeInPast: "stopped_time_must_be_in_past",
    StoppedTimeMustBeGreaterThanStartTime: "stopped_time_must_be_greater_than_start_time",
    TotalTimeMustBePositive: "total_time_must_be_positive",
    TotalTimeOutOfRange: "total_time_out_of_range",
    ScheduleCannotBeCompletedBeforeStartTime: "schedule_cannot_be_completed_before_start_time"

}
export enum ErrorMessageCodes {
    SuperAdministratorsCannotCreateAcademyRequest = "SuperAdministratorsCannotCreateAcademyRequest",
    AcademyRequestRoleIsInvalid = "AcademyRequestRoleIsInvalid",
    TheUserAlreadyExistInTheAcademyWithRole = "TheUserAlreadyExistInTheAcademyWithRole",
    TheUserAlreadyExistInTheAcademy = "TheUserAlreadyExistInTheAcademy",
    AdministratorCannotEnrollTheCourse = "AdministratorCannotEnrollTheCourse",
    TheUserAlreadyEnrolledToTheCourse = "TheUserAlreadyEnrolledToTheCourse",
    YouAlreadySentAnAcademyRequest = "YouAlreadySentAnAcademyRequest",
    AcademyRequestNotFound = "AcademyRequestNotFound",
    UserNotFound = "UserNotFound",
    AcademyRequestAlreadyApproved = "AcademyRequestAlreadyApproved",
    AddUserToAcademyFailed = "AddUserToAcademyFailed",
    AcademyRequestAlreadyRejected = "AcademyRequestAlreadyRejected",
    InvalidRequest = "InvalidRequest",
    MakeUpRecordAlreadyExists = "MakeUpRecordAlreadyExists",
    OriginalLessonAlreadyHasMakeUp = "OriginalLessonAlreadyHasMakeUp",
    MakeUpLessonTimeConflict = "MakeupLessonTimeConflict",
    MakeupLessonConflictWithAnotherMakeup = "MakeupLessonConflictWithAnotherMakeup",
    TheMakeupLessonIsNotStartedYet = "TheMakeupLessonIsNotStartedYet",
    TheMakeupLessonHasEnded = "TheMakeupLessonHasEnded",
    TemplateNotFound = "TemplateNotFound",
    RequiredTemplateName = "RequiredTemplateName",
    RequiredTemplateContent = "RequiredTemplateContent",
    CannotUpdateGlobalTemplate = "CannotUpdateGlobalTemplate",
    CannotDeleteGlobalTemplate = "CannotDeleteGlobalTemplate",
    ExistIncompleteExamSession = "ExistIncompleteExamSession",
    StartTimeMustBeInPast = "StartTimeMustBeInPast",
    StoppedTimeMustBeInPast = "StoppedTimeMustBeInPast",
    StoppedTimeMustBeGreaterThanStartTime = "StoppedTimeMustBeGreaterThanStartTime",
    TotalTimeMustBePositive = "TotalTimeMustBePositive",
    TotalTimeOutOfRange = "TotalTimeOutOfRange",
    ScheduleCannotBeCompletedBeforeStartTime = "ScheduleCannotBeCompletedBeforeStartTime"
}
