import 'dotenv/config';

export default ({ config }) => ({
  ...config,
  extra: {
    ...config.extra,
    BASE_URL: process.env.EXPO_PUBLIC_BASE_URL,
    SUPER_ADMIN_BASE_URL: process.env.EXPO_PUBLIC_SUPER_ADMIN_BASE_URL,
    SOCKET_URL: process.env.EXPO_PUBLIC_SOCKET_URL,
    STUDENT_URL: process.env.EXPO_PUBLIC_STUDENT_URL,
    OTA_URL: process.env.EXPO_PUBLIC_OTA_URL,

    GOOGLE_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_CLIENT_ID,
    ANDROID_GOOGLE_CLIENT_ID: process.env.EXPO_PUBLIC_ANDROID_GOOGLE_CLIENT_ID,
    IOS_GOOGLE_CLIENT_ID: process.env.EXPO_PUBLIC_IOS_GOOGLE_CLIENT_ID,
    WEB_GOOGLE_CLIENT_ID: process.env.EXPO_PUBLIC_WEB_GOOGLE_CLIENT_ID,

    GOOGLE_RECAPTCHA_ID: process.env.EXPO_PUBLIC_GOOGLE_RECAPTCHA_ID,
    GOOGLE_RECAPTCHA_KEY: process.env.EXPO_PUBLIC_GOOGLE_RECAPTCHA_KEY,

    PUSHER_KEY: process.env.EXPO_PUBLIC_PUSHER_CONFIG_KEY,
    PUSHER_CLUSTER: process.env.EXPO_PUBLIC_PUSHER_CONFIG_CLUSTER,
  },
});