import { ScaledSheet } from 'react-native-size-matters'
import { palette } from '@/theme'

export const ss = ScaledSheet.create({
  mainContainer: { backgroundColor: palette.bg[100] },
  subTabNavigation: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderColor: palette.grey[200],
    height: '46@ms',
    zIndex: 10
  },
  subTabButton: { flex: 1, justifyContent: 'center', alignItems: 'center', position: 'relative' },
  subTabButtonActiveLine: {
    position: 'absolute',
    bottom: -1,
    height: '2@ms',
    backgroundColor: palette.main[500],
    width: '68%',
    borderRadius: '1@ms'
  },
  subTabText: { fontSize: '13@ms', fontWeight: '600', color: palette.grey[500] },
  subTabTextActive: { color: palette.main[500] },
  scrollContainer: { paddingBottom: '400@ms', flexGrow: 1, },
  panel: { paddingBottom: '20@ms' },
  section: { padding: '16@ms' },
  mt0: { paddingTop: 0 },
  sectionHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: '10@ms', marginTop: '10@ms' },
  sectionTitleWrap: { position: 'relative', paddingLeft: '9@ms' },
  sectionTitleLine: {
    position: 'absolute',
    left: 0,
    top: '3@ms',
    bottom: '3@ms',
    width: '3@ms',
    backgroundColor: palette.main[500],
    borderRadius: '2@ms'
  },
  sectionTitle: { fontSize: '14@ms', fontWeight: '700', letterSpacing: -0.1, color: '#000' },
  sectionLink: { fontSize: '11.5@ms', color: palette.main[500], fontWeight: '600' },
  sectionHint: { fontSize: '11@ms', color: palette.grey[400] },
  card: { backgroundColor: '#FFFFFF', borderRadius: '14@ms', borderWidth: 1, borderColor: palette.grey[200] },
  emptyState: { padding: '18@ms', alignItems: 'center' },
  emptyTitle: { fontSize: '13@ms', fontWeight: '700', color: palette.grey[900], marginBottom: '4@ms', textAlign: 'center' },
  emptyDesc: { fontSize: '11@ms', color: palette.grey[500], lineHeight: '16@ms', textAlign: 'center' },

  // Summary
  todayHeroWrap: { borderRadius: '16@ms', overflow: 'hidden' },
  todayHero: { padding: '20@ms', position: 'relative' },
  todayHeroCircle: {
    position: 'absolute',
    top: '-50@ms',
    right: '-50@ms',
    width: '160@ms',
    height: '160@ms',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: '80@ms'
  },
  todayLabel: { fontSize: '12@ms', fontWeight: '500', opacity: 0.85, marginBottom: '6@ms', color: '#FFFFFF' },
  todayValue: { fontSize: '36@ms', fontWeight: '800', color: '#FFFFFF', lineHeight: '36@ms' },
  todayValuePct: {
    fontSize: '20@ms',
    fontWeight: '700',
    color: '#FFFFFF',
    marginLeft: '2@ms',
    opacity: 0.9,
    lineHeight: '30@ms'
  },
  todayDelta: { fontSize: '12@ms', fontWeight: '600', color: '#FFFFFF', marginTop: '8@ms', opacity: 0.95 },
  todayStats: { flexDirection: 'row', gap: '8@ms', marginTop: '16@ms' },
  todayStat: { flex: 1, backgroundColor: 'rgba(255,255,255,0.15)', borderRadius: '10@ms', padding: '10@ms' },
  todayStatLabel: { fontSize: '10@ms', opacity: 0.85, marginBottom: '3@ms', color: '#FFFFFF' },
  todayStatValue: { fontSize: '14@ms', fontWeight: '700', color: '#FFFFFF' },
  todayStatValueSub: { fontSize: '10@ms', color: '#FFFFFF', opacity: 0.85, fontWeight: '500' },

  statGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: '10@ms' },
  statCard: {
    flexBasis: '48%',
    flexGrow: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: palette.grey[200],
    borderRadius: '12@ms',
    padding: '14@ms'
  },
  statCardFull: { flexBasis: '100%' },
  statCardLabel: { fontSize: '11@ms', color: palette.grey[500], marginBottom: '6@ms' },
  statCardValue: { fontSize: '20@ms', fontWeight: '800', color: palette.grey[900], lineHeight: '24@ms' },
  statCardValueU: { fontSize: '12@ms', fontWeight: '500', color: palette.grey[500], marginLeft: '2@ms' },
  statCardSub: { fontSize: '10.5@ms', color: palette.grey[500], marginTop: '4@ms' },
  statWeak: { backgroundColor: '#FEF1F1', borderColor: '#FECACA' },
  statWeakValue: { color: palette.error.main, fontSize: '13.5@ms', lineHeight: '19@ms', flex: 1 },
  statStrong: { backgroundColor: '#ECFDF5', borderColor: '#A7F3D0' },
  statStrongValue: { color: '#065F46', fontSize: '15@ms', flex: 1 },
  pctRight: { fontSize: '14@ms', fontWeight: '800', marginLeft: '4@ms' },
  sampleBadgeMini: {
    backgroundColor: 'rgba(255,255,255,0.7)',
    paddingVertical: '1@ms',
    paddingHorizontal: '6@ms',
    borderRadius: '8@ms',
    marginLeft: '4@ms'
  },
  sampleBadgeMiniText: { fontSize: '9.5@ms', fontWeight: '500', color: palette.grey[500] },

  strength: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#A7F3D0',
    borderRadius: '12@ms',
    paddingVertical: '12@ms',
    paddingHorizontal: '14@ms',
    gap: '10@ms'
  },
  strengthIco: { fontSize: '20@ms' },
  strengthText: { fontSize: '11.5@ms', color: '#065F46', lineHeight: '17@ms' },
  strengthPills: { flexDirection: 'row', flexWrap: 'wrap', gap: '5@ms', marginTop: '6@ms' },
  strengthPill: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#A7F3D0',
    paddingVertical: '2@ms',
    paddingHorizontal: '8@ms',
    borderRadius: '10@ms'
  },
  strengthPillText: { fontSize: '10.5@ms', fontWeight: '700', color: '#065F46' },

  weekCard: { padding: '16@ms' },
  weekDots: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: '10@ms' },
  wd: { alignItems: 'center', gap: '4@ms' },
  wdDow: { fontSize: '9.5@ms', color: palette.grey[400], fontWeight: '500' },
  wdDotTodayLv3Wrap: { padding: '2@ms', borderWidth: 2, borderColor: palette.main[100], borderRadius: '15@ms' },
  wdDot: { width: '22@ms', height: '22@ms', borderRadius: '11@ms', backgroundColor: '#F3F4F6' },
  weekSummary: { backgroundColor: palette.bg[100], padding: '8@ms', borderRadius: '8@ms', alignItems: 'center' },
  weekSummaryText: { fontSize: '11.5@ms', color: palette.grey[500] },

  metricRow: { flexDirection: 'row', gap: '8@ms' },
  metricCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: palette.grey[200],
    borderRadius: '12@ms',
    paddingVertical: '12@ms',
    paddingHorizontal: '10@ms',
    minHeight: '70@ms',
    justifyContent: 'space-between'
  },
  metricLabel: { fontSize: '10@ms', color: palette.grey[500], fontWeight: '600' },
  metricValue: { fontSize: '20@ms', color: palette.grey[900], fontWeight: '800', marginTop: '6@ms' },
  metricValueSmall: { fontSize: '12@ms', color: palette.grey[900], fontWeight: '800', marginTop: '6@ms', lineHeight: '16@ms' },
  chartCard: { padding: '16@ms' },
  chartHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12@ms' },
  chartPill: {
    backgroundColor: palette.main[50],
    paddingVertical: '4@ms',
    paddingHorizontal: '11@ms',
    borderRadius: '16@ms'
  },
  chartPillText: { fontSize: '11@ms', fontWeight: '700', color: palette.main[600] },
  chartLegend: { flexDirection: 'row', gap: '10@ms' },
  chartLegendIco: { width: '8@ms', height: '8@ms', borderRadius: '2@ms', marginRight: '4@ms' },
  chartLegendCurr: { backgroundColor: palette.main[500] },
  chartLegendPrev: { backgroundColor: '#E5E7EB' },
  chartLegendText: { fontSize: '10@ms', color: palette.grey[400] },
  bars: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    height: '110@ms',
    paddingHorizontal: '4@ms',
    borderBottomWidth: 1,
    borderColor: palette.grey[200]
  },
  barGroup: { flexDirection: 'row', alignItems: 'flex-end', gap: '3@ms', height: '100%' },
  bar: { width: '10@ms', borderTopLeftRadius: '2@ms', borderTopRightRadius: '2@ms', minHeight: '1@ms' },
  barCurrent: { backgroundColor: palette.main[500] },
  barCompare: { backgroundColor: '#E5E7EB' },
  barLabels: { flexDirection: 'row', justifyContent: 'space-around', marginTop: '6@ms' },
  barLabel: { fontSize: '10@ms', color: palette.grey[400], flex: 1, textAlign: 'center' },

  catCard: { padding: '16@ms' },
  catBar: { flexDirection: 'row', height: '38@ms', borderRadius: '6@ms', overflow: 'hidden', marginBottom: '8@ms' },
  catSeg: { justifyContent: 'center', alignItems: 'center' },
  catSegText: { color: '#FFFFFF', fontSize: '11.5@ms', fontWeight: '700' },
  catLabelName: { fontSize: '10.5@ms', fontWeight: '600', textAlign: 'center' },
  catLabelPct: { fontSize: '10@ms', fontWeight: '500', color: palette.grey[500], textAlign: 'center' },

  midcatCard: { padding: '16@ms' },
  midcatLegend: { flexDirection: 'row', justifyContent: 'flex-end', gap: '10@ms', marginBottom: '8@ms' },
  midcatLegendIco: { width: '7@ms', height: '7@ms', borderRadius: '3.5@ms', marginRight: '3@ms' },
  midcatLegendText: { fontSize: '10@ms', color: palette.grey[500] },
  midcatRow: { paddingVertical: '8@ms', borderBottomWidth: 1, borderColor: palette.grey[200] },
  midcatRowTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: '5@ms' },
  midcatLabel: { fontSize: '12.5@ms', fontWeight: '600', color: '#000' },
  sampleMini: {
    backgroundColor: '#F3F4F6',
    paddingVertical: '1@ms',
    paddingHorizontal: '5@ms',
    borderRadius: '6@ms',
    marginLeft: '4@ms'
  },
  sampleMiniText: { fontSize: '9@ms', fontWeight: '500', color: palette.grey[500] },
  midcatMeta: { flexDirection: 'row', alignItems: 'center', gap: '8@ms' },
  midcatMetaFrac: { fontSize: '10.5@ms', color: palette.grey[500] },
  trUp: { fontSize: '10.5@ms', color: palette.success.main, fontWeight: '700' },
  trDown: { fontSize: '10.5@ms', color: palette.error.main, fontWeight: '700' },
  trFlat: { fontSize: '10.5@ms', color: palette.grey[400] },
  midcatBarWrap: { backgroundColor: '#F3F4F6', borderRadius: '4@ms', height: '20@ms', overflow: 'hidden' },
  midcatFill: { height: '100%', borderRadius: '4@ms', justifyContent: 'center', paddingLeft: '8@ms' },
  midcatFillText: { fontSize: '10.5@ms', fontWeight: '700', color: '#FFFFFF' },
  midcatTip: {
    marginTop: '10@ms',
    paddingVertical: '10@ms',
    paddingHorizontal: '12@ms',
    backgroundColor: palette.main[50],
    borderRadius: '8@ms'
  },
  midcatTipText: { fontSize: '11@ms', color: palette.main[600], lineHeight: '16@ms' },

  peerCard: { padding: '16@ms' },
  peerBars: { gap: '8@ms', marginVertical: '10@ms' },
  peerRow: { flexDirection: 'row', alignItems: 'center', gap: '10@ms' },
  peerLabel: { width: '85@ms', fontSize: '11.5@ms', color: palette.grey[500] },
  peerBarWrap: { flex: 1, backgroundColor: '#F3F4F6', borderRadius: '4@ms', height: '22@ms' },
  peerBar: { height: '100%', borderRadius: '4@ms', justifyContent: 'center', paddingHorizontal: '8@ms' },
  peerBarMe: { backgroundColor: palette.main[500] },
  peerBarAvg: { backgroundColor: '#9CA3AF' },
  peerBarText: { fontSize: '10.5@ms', fontWeight: '700', color: '#FFFFFF' },
  peerGap: {
    backgroundColor: palette.main[50],
    padding: '8@ms',
    borderRadius: '8@ms',
    marginTop: '8@ms',
    alignItems: 'center'
  },
  peerGapText: { fontSize: '11@ms', color: palette.main[600], textAlign: 'center' },
  arrowDown: { color: '#EF4444', fontWeight: '700' },
  catchUp: { color: '#10B981', fontWeight: '700' },

  weakList: { gap: '10@ms' },
  weakItem: {
    borderRadius: '14@ms',
    paddingVertical: '14@ms',
    paddingHorizontal: '16@ms',
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: '12@ms'
  },
  weakItemR1: { backgroundColor: '#FECACA', borderColor: '#F87171' },
  weakItemR2: { backgroundColor: '#FEF1F1', borderColor: '#FECACA' },
  weakItemR3: { backgroundColor: '#FFF4EA', borderColor: '#FED7AA' },
  weakItemR4: { backgroundColor: '#FFF8EE', borderColor: '#FDE68A' },
  weakRankBadge: {
    width: '44@ms',
    height: '44@ms',
    borderRadius: '22@ms',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center'
  },
  weakRankNum: { fontSize: '16@ms', fontWeight: '800', lineHeight: '16@ms' },
  weakRankLabel: { fontSize: '8.5@ms', fontWeight: '700', color: palette.grey[500], marginTop: '1@ms' },
  weakBody: { flex: 1 },
  weakName: { fontSize: '13@ms', fontWeight: '700', lineHeight: '17@ms', color: palette.grey[900], marginBottom: '5@ms' },
  weakTags: { flexDirection: 'row', flexWrap: 'wrap', gap: '4@ms', marginBottom: '5@ms' },
  weakTag: {
    backgroundColor: 'rgba(255,255,255,0.85)',
    paddingVertical: '2@ms',
    paddingHorizontal: '7@ms',
    borderRadius: '4@ms'
  },
  weakTagText: { fontSize: '10@ms', fontWeight: '500', color: palette.grey[700] },
  weakMeta: { flexDirection: 'row', alignItems: 'center', gap: '8@ms' },
  weakFrac: { fontSize: '10.5@ms', color: palette.grey[500] },
  weakTrend: { fontSize: '10.5@ms', fontWeight: '700' },
  weakTrendDown: { color: '#EF4444' },
  weakTrendUp: { color: '#10B981' },
  weakTrendNew: {
    backgroundColor: 'rgba(255,255,255,0.7)',
    color: palette.grey[700],
    paddingVertical: '1@ms',
    paddingHorizontal: '7@ms',
    borderRadius: '8@ms',
    fontSize: '9.5@ms',
    fontWeight: '400'
  },
  weakPctBig: { fontSize: '26@ms', fontWeight: '800', lineHeight: '26@ms' },
  weakPctBigP: { fontSize: '13@ms', fontWeight: '700' },

  tblFilters: { flexDirection: 'row', marginBottom: '10@ms' },
  tblFilter: {
    paddingVertical: '5@ms',
    paddingHorizontal: '12@ms',
    borderRadius: '14@ms',
    borderWidth: 1,
    borderColor: palette.grey[300],
    backgroundColor: '#FFFFFF'
  },
  tblFilterActive: { borderColor: palette.main[500], backgroundColor: palette.main[50] },
  tblFilterText: { fontSize: '11.5@ms', fontWeight: '500', color: palette.grey[500] },
  tblFilterTextActive: { color: palette.main[500], fontWeight: '700' },
  typesList: { gap: '8@ms' },
  typeRow: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: palette.grey[200],
    borderRadius: '10@ms',
    paddingVertical: '12@ms',
    paddingHorizontal: '14@ms'
  },
  typeRowRRed: { backgroundColor: '#FEF2F2', borderColor: '#FECACA' },
  typeRowRAmber: { backgroundColor: '#FFFBEB', borderColor: '#FDE68A' },
  typeRowRYellow: { backgroundColor: '#FEFCE8', borderColor: '#FEF08A' },
  typeRowHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '10@ms',
    marginBottom: '6@ms'
  },
  typeName: { fontSize: '13@ms', fontWeight: '700', lineHeight: '17@ms', color: '#000', flex: 1 },
  pctPill: {
    paddingVertical: '4@ms',
    paddingHorizontal: '10@ms',
    borderRadius: '5@ms',
    minWidth: '48@ms',
    alignItems: 'center'
  },
  pctPillRed: { backgroundColor: '#EF4444' },
  pctPillOrange: { backgroundColor: '#F97316' },
  pctPillAmber: { backgroundColor: '#F59E0B' },
  pctPillGreen: { backgroundColor: '#10B981' },
  pctPillText: { fontSize: '11.5@ms', fontWeight: '700', color: '#FFFFFF' },
  typeMeta: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  typeTags: { flexDirection: 'row', gap: '6@ms' },
  typeTag: {
    backgroundColor: '#FFFFFF',
    paddingVertical: '2@ms',
    paddingHorizontal: '7@ms',
    borderRadius: '4@ms',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.04)'
  },
  typeTagText: { fontSize: '10@ms', color: palette.grey[700] },
  fracLast: { fontSize: '10.5@ms', color: palette.grey[500] },
  fracDone: { fontWeight: '700', color: palette.grey[900] },
  typesMore: {
    textAlign: 'center',
    paddingTop: '14@ms',
    paddingBottom: '4@ms',
    color: palette.main[500],
    fontSize: '12.5@ms',
    fontWeight: '700'
  }
})
