name: Upload IPA to TestFlight

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: 'Direct URL of the IPA file from Expo'
        required: true

jobs:
  upload:
    runs-on: macos-latest
    steps:
      - name: Download IPA File
        run: |
          curl -L "${{ github.event.inputs.ipa_url }}" -o app.ipa

      - name: Upload to App Store Connect
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASS: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          xcrun altool --upload-app -f app.ipa -t ios -u "$APPLE_ID" -p "$APPLE_PASS" --end-user-licensing-agreement YES
